# postgres config
spring.datasource.url=jdbc:postgresql://localhost:5432/car_store
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# port
server.port=8085

# kafka configs
spring.kafka.bootstrap-servers=localhost:9092